build:
    tests:
        override:
            -
                command: vendor/bin/phpunit
                coverage:
                    file: 'test-coverage-report/clover.xml'
                    format: 'clover'
